### ISSUE TITLE
[BUG] I can't open the backpacks with right click

### ISSUE THREAD

**Issue by WasaTG** [PluginBugs/Issues-EpicBackpacks#38] opened 2021-09-26 17:21 UTC
**Describe the bug**
When I want to right-click to open a backpack from the EpicBackPacks, nothing happens. I can give myself the backpacks and the plugin works fine, but it won't let me right click on the backpack items to open them

**To Reproduce**
1. Go to 'give a backpack'
2. Click on 'right click on the item received.'
3. See error https://pastebin.com/ZSaD9Pyz

**Expected behavior**
When I right click absolutely nothing happens, I cannot open my backpack

**Info (please complete the following information):**
 - Server version: Paper 1.12.2
 - Client version: 1.12.2)
 - Plugin version: 1.3.9

**Comment by LoneDev6** [comment] 2021-09-27 13:12
This will be looked further and fixed in the next days.
Have a nice day

**Comment by LoneDev6** [comment] 2022-01-13 08:30
Let me know if the issue is still there in the latest version of the plugin

**Closed by LoneDev6** 2022-01-13 08:30 UTC
Labels: bug
