### ISSUE TITLE
Could not pass event InventoryCreativeEvent

### ISSUE THREAD

**Issue by EchocallingEarth** [PluginBugs/Issues-EpicBackpacks#102] opened 2023-09-12 20:58 UTC
**Describe the bug**
ERROR Could not pass event InventoryCreativeEvent to EpicBackpacks v1.3.16-r4, caused by dropping full stack of heads from creative inventory.

**To Reproduce**
Start server
Set gamemode to Creative(did not test in survival)
Give yourself a stack of heads (can be vanilla, hdb or other (such as from a datapack)
Open inventory grab the entire stack and drop it on the ground 
_Do not drop heads 1 at a time it must be the full stack all at once to cause the error_

**Expected behavior**
No errors in the console when a stack of heads is dropped from an admin/player inventory.

**Screenshots**
NA

**Info (please complete the following information):**
 - Purpur 1.20.1
 - NA
 - EpicBackpacks v1.3.16-r4

**Additional context**
Error log:
[https://pastebin.com/KxM7dnpR]

_Important I only tested this in creative as I feel that if the issue is also survival or adventure it should be checked separately and reported that way as it states in the error CreativeInventory_

Full list of plugins:
AdvancedClaimGuardian, Arceon, ArmoredElytra, AureliumSkills, Bank, BetterLogStrip, BetterTridents, BigDoors, BlockEffects, BlockProt, BlueMap, ccNoEnderpearlDamage, ChatControlRed, ChestSort, Citizens, CitizensGUI, ClearFog, CMI, *CMIEInjector, CMILib,  *ConsoleSay, ConsoleSpamFix, Core, CraftaroCore, CraftBook, CustomCrafting, DecentHolograms, DisplayShops, DoorsReloaded, dtlTradersPlus, EpicBackpacks, EpicFurnaces, ExecutableBlocks, ExecutableItems, FastAsyncWorldEdit, FastChunkPregenerator, GadgetsMenu, goBrush, goPaint, HeadDatabase,  ImageFrame, InteractiveBoard, ItemsAdder, ItemsAdder-WorldEdit, Jobs, LibsDisguises, LightCleaner, LoneLibs, Lootin, LuckPerms,  PerWorldInventory, PhatLoots, PlaceholderAPI, PlotSquared, ProtocolLib, PublicCrafters, RealisticSeasons, RealisticVillagers, SCore, spark, VirtualBooks, Wailat, WorldGuard

Note as we use a custom plugin for claiming (AdvancedClaimGuardian) I can provide this via a secure method (Discord or email for testing if required)

If additional information is needed I will do as much as I can to provide any info accurately and in a manner in which to fix this issue.

**Comment by LoneDev6** [comment] 2023-09-13 13:45
Will be checked as soon as possible

**Comment by EchocallingEarth** [comment] 2023-09-13 14:03
Again if you need additional details or testing please feel free to reach out. And I will do all I can to assist.

**Comment by EchocallingEarth** [comment] 2023-09-27 01:50
Update - Tested in Survival and does not appear to be an issue. However, this is not a true test as I am sure you have ways to dig deeper than I do. I hope this extra info is useful in moving toward a fix in the near future. Thanks, and as always loving the plugins and appreciate all your hard work.

**Comment by LoneDev6** [comment] 2023-09-29 11:53
Duplicate of #101

**Closed as not planned by LoneDev6** 2023-09-29 11:53 UTC
Labels: duplicate
