### ISSUE TITLE
[BUG] Backpack

### ISSUE THREAD

**Issue by deleeteexe** [PluginBugs/Issues-EpicBackpacks#83] opened 2023-02-07 17:24 UTC
**Describe the bug**
When trying to open the backpack getting error which doing the backpack is loading to the infinity

**To Reproduce**
1. Download the plugin and https://www.spigotmc.org/resources/freddiesbackpacks-%E2%AD%95-itemsadder-epicbackpacks-addon-%E2%AD%90.107766/
2. Try to add any backpack (yeah i tried most of them)
3. Open the backpack
4. See the error

**Expected behavior**
The Backpack Should open

**Info (please complete the following information):**
 - Server version: Paper 1.19.3
 - Client version: Fabric 1.19,3
 - Plugin version: 1.3.16-r2

**Additional context**
Console LOGS

[12:00:39] [Server thread/INFO]: [EpicBackpacks] Loading EpicBackpacks v1.3.16-r2
[12:00:59] [Server thread/INFO]: [EpicBackpacks] Enabling EpicBackpacks v1.3.16-r2
[12:01:00] [Server thread/INFO]: 
[12:01:00] [Server thread/INFO]: -=[ EpicBackPacks ]=-
[12:01:00] [Server thread/INFO]: 
[12:01:00] [Server thread/INFO]: Version: 1.3.16-r2
[12:01:00] [Server thread/INFO]: Server version: v1_19_R2
[12:01:00] [Server thread/INFO]: 
[12:01:00] [Server thread/INFO]: 
[12:01:00] [Server thread/INFO]: [EpicBackpacks] §eWaiting ItemsAdder to register custom items...
[12:01:04] [Server thread/INFO]: [EpicBackpacks] §aItemsAdder finished loading, now loading backpacks...
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: adididas_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: niike_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: supreme_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: purple_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_casualbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_hikingbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_schoolbackpack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: purple_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: lime_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: gray_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: yellow_shoppingbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: purple_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_suitcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_sportbag
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: purple_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: gray_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: yellow_sportbag2
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: cyan_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: gray_briefcase
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: niike_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: adididas_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: supreme_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: yellow_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: cyan_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: purple_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: pink_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: black_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: white_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: green_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: red_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: orange_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: blue_fannypack
[12:01:04] [Server thread/INFO]: [EpicBackpacks] §aLoaded backpacks correctly
[17:15:14] [Server thread/INFO]: XXX issued server command: /ebpget adididas_fannypack
[17:15:15] [Craft Scheduler Thread - 356 - EpicBackpacks/WARN]: [EpicBackpacks] Plugin EpicBackpacks v1.3.16-r2 generated an exception while executing task 402078
java.lang.ClassCastException: class net.minecraft.nbt.NBTTagCompound cannot be cast to class java.util.Set (net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @e2144e4; java.util.Set is in module java.base of loader 'bootstrap')
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:588) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getKeys(NBTCompound.java:542) ~[LoneLibs.jar:?]
	at dev.lone.EpicBackpacks.a.a(SourceFile:431) ~[EpicBackpacks_1.3.16-r2.jar:?]
	at dev.lone.EpicBackpacks.a.a(SourceFile:373) ~[EpicBackpacks_1.3.16-r2.jar:?]
	at dev.lone.EpicBackpacks.e.a(SourceFile:140) ~[EpicBackpacks_1.3.16-r2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-372]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment] 2023-03-10 10:24
Duplicate of https://github.com/PluginBugs/Issues-EpicBackpacks/issues/82

**Closed by LoneDev6** 2023-03-10 10:24 UTC
Labels: bug
