### ISSUE TITLE
[Suggestion] Opening EBP when Players are offline

### ISSUE THREAD

**Issue by xDodi** [PluginBugs/Issues-EpicBackpacks#100] opened 2023-08-23 08:18 UTC
**Is your feature request related to a problem? Please describe.**
When i ban player for cheating or something i can't search his Backpack beacause his offline and sometimes players steal someones items and hide it in ebp.

**Describe the solution you'd like**
I want to open EBP from other players when they are offline

**Describe alternatives you've considered**
No other options

**Additional context**
Keeping server Fair and Clear is hard and this would make my life a lot easier

**Comment by LoneDev6** [comment] 2023-09-06 10:08
Hello,
Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!

**Comment by xDodi** [comment] 2023-09-06 10:13
No worries I appreciate that you even answered

LoneDev ***@***.***> schrieb am Mi., 6. Sept. 2023, 12:08:

**Comment by LoneDev6** [comment] 2023-09-11 13:40
Duplicate of https://github.com/PluginBugs/Issues-EpicBackpacks/issues/58

**Closed as not planned by LoneDev6** 2023-09-11 13:40 UTC
Labels: duplicate
